### ISSUE TITLE
download file app-name.zip with JDK17 not able to build with gradle

### ISSUE THREAD

**Issue by aknguyen7** [OpenLiberty/start.openliberty.io#106]
1. in OL.io go to starter, download file with JDK17 with gradle
2. unzip app-name.zip, cd to app-name directory and run gradlew libertyDev
```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/aknguyen/Liberty/libertyGit/openliberty.io/src/test/cypressjs/cypress/downloads/app-name-jdkseventeen-g-jktnineone-none/build.gradle'

* What went wrong:
Could not compile build file '/Users/aknguyen/Liberty/libertyGit/openliberty.io/src/test/cypressjs/cypress/downloads/app-name-jdkseventeen-g-jktnineone-none/build.gradle'.
> startup failed:
  General error during semantic analysis: Unsupported class file major version 61
  
  java.lang.IllegalArgumentException: Unsupported class file major version 61
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:196)
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:177)
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:163)
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:284)
  	at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:81)
  	at org.codehaus.groovy.control.ClassNodeResolver.findDecompiled(ClassNodeResolver.java:251)
  	at org.codehaus.groovy.control.ClassNodeResolver.tryAsLoaderClassOrScript(ClassNodeResolver.java:189)
```

I think the JDK17 does not support the current gradle version. I tried to move to gradle 7.3 base on https://docs.gradle.org/current/userguide/compatibility.html
but it breaks older stuffs. Need more investgation

**Comment by mattbsox** [comment]
From what I'm finding with some quick searches, Gradle might not fully support JDK17 at this time.

Adding `-i -s` flags to the command might give more info.

**Comment by mattbsox** [comment]
Looks like the current Gradle wrapper version being packaged with the starter applications is `6.9.2`.

Gradle `7.x` needs to be used in order to run with JDK17.

The wrapper version should be updated to a `7.x` version. The latest is [7.5.1](https://gradle.org/releases/).

**Comment by kinueng** [comment]
Fixed by https://github.com/OpenLiberty/start.openliberty.io/pull/143
