### ISSUE TITLE
Unnecessary message when selecting `None` for MicroProfile Version

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/start.openliberty.io#107]
**Describe the bug**  
A message indicating a Version parameter has been changed when selecting `None` for MicroProfile Version is unnecessary. No parameter was actually changed when the message is shown.

![image](https://user-images.githubusercontent.com/31117513/169136252-5f3b1950-2930-43b1-9d9c-1b5ae73965c8.png)

**Steps to Reproduce**  
1. Select `None` for MicroProfile version
1. Observe the unexpected message `Java EE / Jakarta EE Version has been automatically updated to default Version 9.1 since MicroProfile Version has been selected as None .`

**Expected behavior**  
The unexpected message is unnecessary because `9.1` is already selected as default for `Java EE/Jakarta EE Version`

**Diagnostic information:**
 - Group [e.g. com.demo]
 - Artifact [e.g. app-name]
  - Build Tool
    - [x] Maven
    - [ ] Gradle
 - Java SE Version [11]
 - Java EE/Jakarta EE Version [9.1]
 - MicroProfile Version [None]

**Comment by Sreejith-Websphere** [comment]
Also @kin in this chat https://ibm-cloud.slack.com/archives/C4U7TQUSY/p1652865831763309 The Nones need to be considered compatible with all versions of the other spec. so along with not showing message for None they can select any other versions vice-versa, now when they select None in Java EE/Jakarta EE Version 5.0 in MicroProfile Version will be selected and when they select None in Microprofile Version 9.1 in  Java EE/Jakarta EE Version will be selected
