### ISSUE TITLE
Bad performance if server.xml is using microProfile and/or jakartaee

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/start.openliberty.io#108]
In my experience for the liberty-deep-dive guide (masterclass v2), the guide starts from a OL starter project. The server.xml uses microProfile and/or jakartaee features. When start the dev mode, it takes a long while. It gives users a bad impression that liberty has performance issue. Dev mode may timeout easily. Because the Dockerfile use kernel-slim image, the docker build time is long too.

The LMP auto-generated features may be the solution. If it is, server.xml should have no feature.

**Comment by gkwan-ibm** [comment]
@yeekangc

**Comment by gkwan-ibm** [comment]
same as #109

**Comment by steven1046** [comment]
Can we copy the information here into 109 and close this issue?

**Comment by gkwan-ibm** [comment]
close
- this issue will be addressed by #109
