### ISSUE TITLE
Add error support for curl

### ISSUE THREAD

**Issue by Jonathan-Maciel** [OpenLiberty/start.openliberty.io#110]
**Describe your idea for new feature to add to the Liberty Starter**  
Send a message in the response showing how to properly format the request.

**Describe why the new feature is important**  
Users may be confused when the response returns an error, if they are not formatting the group or artifact names properly. It would be nice to know where the request failed, or just get a general message on proper format.

**Any additional context**  
```
curl -o ./app-name.zip "https://start.openliberty.io/api/start?a=wrong.name&b=maven&e=9.1&g=com.demo&j=11&m=5.0" -v

...

> GET /api/start?a=wrong.name&b=maven&e=9.1&g=com.demo&j=11&m=5.0 HTTP/2
> Host: start.openliberty.io
> user-agent: curl/7.79.1
> accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
< HTTP/2 400 

```

**Comment by chungngoops** [comment]
I'm working on this issue.
