### ISSUE TITLE
Liberty Starter page does not properly validate maven group ID

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/start.openliberty.io#135]
**Describe the bug**  
On https://openliberty.io/start/ you can choose a maven group name but it restricts you to `a-z` separated by `.`. It is perfectly valid to use numbers, underscores and capitals in a maven group ID. The maven docs say that group IDs should follow the same rules as Java package names.
https://maven.apache.org/guides/mini/guide-naming-conventions.html
https://docs.oracle.com/javase/specs/jls/se6/html/packages.html#7.7

**Steps to Reproduce**  
Go to https://openliberty.io/start/ and set the maven ID to `com.Acme.my_widget.v2`

**Expected behavior**  
Capitals, underscores and numbers should be allowed (and any other chars allowed by java package names, I haven't double checked).

**Diagnostic information:**
 - Group `com.Acme.my_widget.v2`
  - Build Tool
    - [x] Maven
    - [ ] Gradle

**Comment by tevans78** [comment]
Same applies to the artifact ID as well

**Comment by Sreejith-Websphere** [comment]
@tevans78 is the same rule should be applicable for Gradle groupId also? please confirm

cc @kinueng @natalie-bernhard

**Comment by Sreejith-Websphere** [comment]
@kinueng 

Here is the branches I worked (maven_groupID_validation_change_135)

https://github.com/OpenLiberty/openliberty.io/compare/maven_groupID_validation_change_135?expand=1

https://github.com/OpenLiberty/start.openliberty.io/compare/maven_groupID_validation_change_135?expand=1

**Comment by amyreit** [comment]
Looks like gradle doesn't have the same rigid requirements but for simplicity for our sake, I think we can do what Sreejith had started and enforce all lower case for the first package and then allow A-Z, 0-9 and '_' for the other sub packages with each package separated by '.'
