### ISSUE TITLE
Automate E2E Cypress Functional Tests for Open Liberty Starter

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/start.openliberty.io#146]
# Problem
The Cypress tests for the Open Liberty Starter have to be run manually by a developer. Look for ways to automate the end-to-end Cypress tests against the live staging site https://staging-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/start/.

# Challenge
The challenge here is that the tests expect the test machine to have JDK8, JDK11, and JDK 17 installed. Developers have to have all three JDK versions on their laptops before running the tests manually.  See this file on how each developer can change the location of the JDKs on their local machine https://github.com/OpenLiberty/openliberty.io/blob/prod/src/test/cypressjs/cypress.env.json

I would like for the test runs and results be accessible from the public since the starter is open source. One way is to evaluate using GitHub actions as an engine for running the Cypress tests. Here is the Cypress GitHub action https://github.com/cypress-io/github-action

# Tasks
We should move Open Liberty Starter Cypress tests from the `OpenLiberty/openliberty.io` repo to this repo. Tests can be found here https://github.com/OpenLiberty/openliberty.io/tree/prod/src/test/cypressjs/cypress/integration

# Additional JUnit tests
I have confirmed that these JUnit tests are always run during build. This is informational but good to remember these JUnit tests are there.
https://github.com/OpenLiberty/start.openliberty.io/tree/main/src/test/java/io/openliberty/website/starter

# Solution - Amy Reitmeyer
I have created two github actions that will replicate most of what the cypress tests were doing. One tests the maven versions and one tests the gradle versions.  The action runs one job that uses a cypress container to execute the cypress tests that select all the combinations of java/ee/mp and downloads the zip files and then asynchronously runs all the jobs that test each of the zip files in an ubuntu container using script commands to unzip, run the maven or gradle commands to build and start the server, and then runs a curl command on the url of the website for the server to make sure that the splash page is there. I was unable to use the cypress test to do the unzip/build process because of the memory limitations of the cypress docker container that the action uses.  So, the curl command is not quite as thorough as a cypress test which would check for items in the browser. Manual visual inspection of the url should still be done.

**Comment by kinueng** [comment]
I also think we should move the Open Liberty starter tests from the `OpenLiberty/openliberty.io` repo to this repo.

**Comment by amyreit** [comment]
The solution has been merged into main - 5/8/2023
