### ISSUE TITLE
Add Java SE 21 as a parameter choice to the Open Liberty Starter application

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/start.openliberty.io#157]
**Describe your idea for new feature to add to the Liberty Starter**  

Java SE 21 is going to be the next LTS. We will need to add `21` as an option to the Open Liberty Starter `Java SE` list

Oracle page showing Java SE 21 target GA is September 2023
https://www.oracle.com/java/technologies/java-se-support-roadmap.html

**Comment by steven1046** [comment]
The website above shows general availability on 

2023/09/19 |   | General Availability
-- | -- | --

**Comment by steven1046** [comment]
https://developer.ibm.com/languages/java/semeru-runtimes/downloads/ shows only Java 20 is out right now

**Comment by natalie-bernhard** [comment]
This needs to be discussed at the stakeholder meeting to see how we want to approach this since a few things in the starter depend on the availability of IBM Semeru Java 21
