### ISSUE TITLE
Upgrade Gradle Wrapper to 8.x

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/start.openliberty.io#161]
Depends on https://github.com/OpenLiberty/ci.gradle/issues/799

When the Liberty Gradle Plugin supports Gradle 8.x, the Gradle wrapper provided by the starter needs to also move from 7.6 to 8.x.

> Ensure the starter also upgrades to the LGP release containing the Gradle 8.x support when delivering the changes to upgrade the Gradle Wrapper to 8.x!

An example of how the starter moved up to Gradle wrapper 7.6 if the person working this issue is not an Gradle SME. https://github.com/OpenLiberty/start.openliberty.io/pull/145

An example of the deprecated message when running `gradlew libertyDev` that shows up on CLI is
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

**Comment by gkwan-ibm** [comment]
No matter which version, it is better to avoid deprecated messages as much as possible.
