### ISSUE TITLE
Enforce Java 11 or higher when selecting Jakarta EE 10 and/or MicroProfile 6.0

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/start.openliberty.io#172]
I am working on EE10 and MP6. I found JDK8 is not compatible to them, so I got
```
[ERROR] COMPILATION ERROR : 
[ERROR] /Users/gkwan/tasks/CNAI/guides/working/getting-started/version-update-mp6/guide-getting-started/finish/src/main/java/io/openliberty/sample/system/SystemReadinessCheck.java:[14,34] cannot access jakarta.enterprise.context.ApplicationScoped
  bad class file: /Users/gkwan/.m2/repository/jakarta/platform/jakarta.jakartaee-api/10.0.0/jakarta.jakartaee-api-10.0.0.jar(jakarta/enterprise/context/ApplicationScoped.class)
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project guide-getting-started: Compilation failure
[ERROR] /Users/gkwan/tasks/CNAI/guides/working/getting-started/version-update-mp6/guide-getting-started/finish/src/main/java/io/openliberty/sample/system/SystemReadinessCheck.java:[14,34] cannot access jakarta.enterprise.context.ApplicationScoped
[ERROR]   bad class file: /Users/gkwan/.m2/repository/jakarta/platform/jakarta.jakartaee-api/10.0.0/jakarta.jakartaee-api-10.0.0.jar(jakarta/enterprise/context/ApplicationScoped.class)
```
Although the default is Java 11, EE10, and MP6, I think the [starter](https://openliberty.io/start/) should check more, show a warning or change the Java version to 11 if users select Java8, EE10, and/or MP6.

**Comment by kinueng** [comment]
I have transferred this issue to start.openliberty.io. The code that enforces correct permutations between Java/EE/MP is in this repo's code.

**Comment by kinueng** [comment]
It was confirmed that Jakarta EE 10 needs to paired with Java 11 or higher.

The starter is already coded to force EE10 to always be paired with MP6.0. An additional enforcement needs to also ensure that a Java 11 or higher is selected. If the user selects Java 17, **do not** downgrade the choice to Java 11. 

We already have this frustrating UX problem with the `None` choice tracked here https://github.com/OpenLiberty/openliberty.io/issues/3117

**Comment by amyreit** [comment]
I have modified the code to validate that if either MP 6.0 or EE 10 is chosen then the java must be at least 11. If it's set to 8, we will force it to 11 and put up a message that we have done so.

**Comment by amyreit** [comment]
9.1/5.0 and None/5.0 do work with java 8 - the github action needs debug. Jared and Emily agree it works. Not sure why it's not certified.
