### ISSUE TITLE
Allow None options when selecting Jakarta EE and MicroProfile versions

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/start.openliberty.io#21]
From the starter at https://openliberty.io/start/

**Comment by mbroz2** [comment]
We don't want the option to select None for both.

**Comment by kinueng** [comment]
We will need to introduce new logic for `None`.  When none is chosen, we need to remove the feature from the `pom.xml` and `build.gradle` files that are provided to the end user.

**Comment by steven1046** [comment]
> We will need to introduce new logic for `None`. When none is chosen, we need to remove the feature from the `pom.xml` and `build.gradle` files that are provided to the end user.

And `server.xml` in the template used to generate the starter project.

**Comment by Sreejith-Websphere** [comment]
Need to know how to handle None option since in our server.xml,build.gradle,pom.xml it depends on ${microProfileVersion} ${jakartaEEVersion} while building the project, so how we should procced with none option while building the project

**Comment by kinueng** [comment]
In production, closing
