### ISSUE TITLE
Comments on Readme in starter

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/start.openliberty.io#22]
1. I don’t think it adds much to list all of the generated files as you can see them clearly.

1. When you generate the starter, you will know whether you choose maven or gradle. 
The readme should contain the corresponding instructions for the maven/gradle info not listing all of them.

**Comment by aknguyen7** [comment]
Verified in Production

Readme.txt using Gradle
![image](https://user-images.githubusercontent.com/30509453/160439673-f75fa179-556e-492b-9d54-2b6ee093b5a4.png)

Readme.txt using Maven
![image](https://user-images.githubusercontent.com/30509453/160439766-22d53826-b5b8-4a93-b5af-4071e30e58ef.png)
