### ISSUE TITLE
Create a staging environment for the starter

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/start.openliberty.io#27]
This includes:

- A staging branch that new code must be delivered into to test before it goes into main
- A new IBM Cloud pipeline to build the staging starter app
- README instructions for this repo to deliver code into staging then main

**Comment by kinueng** [comment]
The end goal is to have the staging website (e.g. https://ui-staging-openlibertyio.mybluemix.net/) call the staging starter API (e.g. https://start-beta.openliberty.io/api/start/info)

**Comment by kinueng** [comment]
There is still not any Code Engine CI/CD setup so I will leave this opened as partially done

**Comment by kinueng** [comment]
The new CF based staging site and toolchain are now all setup.  https://staging-starter.mybluemix.net/api/start/info

**Comment by kinueng** [comment]
Done
