### ISSUE TITLE
Starter to use latest versions of Maven & Gradle plugins

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/start.openliberty.io#28]
We recently released LMP 3.5 (see ci.maven for details) and LGP 3.3 (see ci.gradle for details).  Update Starter to use these releases of the Maven and Gradle plugins.

Cc @cherylking

**Comment by k8vance88** [comment]
Depend a bot might be useful here to indicate when there are new versions. We would not want to auto integrate these changes as they need to be tested. Automated testing would be a bonus.

**Comment by yeekangc** [comment]
The starter is setting projects to use Liberty Maven Plugin 3.3.4 atm, which is pretty old.

Can we update to use the latest as soon as possible?  @kinueng 

Thanks.
