### ISSUE TITLE
Update mvnw version to 3.8.5?

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/start.openliberty.io#82]
We seem to be using 3.6.3 about 2.5 years old per:
https://maven.apache.org/docs/history.html

Should we bump up to 3.8.5?

**Comment by kinueng** [comment]
@steven1046 Do you have any concerns about upgrading `mvnw` to a higher version?  Can you give some background on how the current `3.6.3` version was chosen to be used in the OL Starter?

**Comment by kinueng** [comment]
We should also look at the Gradle tool to see if it needs upgrading too.
